# Generated by Django 4.2 on 2024-04-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
